"""
MedIntel AI — Phase 8: Offline Mock GenAI Provider.

Provides deterministic, offline educational explanations and translations
without making external network calls or requiring an API key.

Guarantees:
    - 100% offline; zero network calls.
    - Zero API keys required.
    - Complete preservation of medical values, units, classifications, probabilities, and bands.
    - Non-diagnostic, non-prescriptive educational wording.
    - Explicit simulation disclosure: Never pretends to be a real LLM.
"""

from typing import Any, Dict, List, Optional, Tuple

from app.schemas.genai import (
    AnalyteExplanationItem,
    DetailLevel,
    GenAIExplainRequest,
    GenAIExplanationPayload,
    RiskExplanationItem,
    SupportedLanguage,
)
from app.services.genai.base import BaseGenAIProvider


# Educational descriptions for core laboratory analytes
_ANALYTE_EDUCATIONAL_DESCRIPTIONS: Dict[str, str] = {
    "glucose": "Glucose is the main type of sugar in blood and the primary source of energy for body cells.",
    "fasting blood glucose": "Fasting blood glucose measures blood sugar levels after an overnight fast to assess metabolic health.",
    "hba1c": "HbA1c measures average blood sugar levels over the past 2 to 3 months attached to hemoglobin.",
    "hemoglobin": "Hemoglobin is an iron-rich protein in red blood cells that carries oxygen throughout the body.",
    "platelets": "Platelets are blood cells that help blood clot to stop bleeding from cuts or injuries.",
    "creatinine": "Creatinine is a normal waste product from muscle metabolism filtered out of the blood by the kidneys.",
    "serum creatinine": "Serum creatinine is a waste product filtered out by kidneys; measuring it helps evaluate kidney filtration function.",
    "blood urea nitrogen": "Blood urea nitrogen measures the amount of nitrogen in blood that comes from the waste product urea.",
    "total cholesterol": "Total cholesterol measures all cholesterol types in blood, including LDL and HDL lipoproteins.",
    "blood pressure": "Blood pressure measures the pressure of circulating blood against blood vessel walls.",
}

# Educational descriptions for ML risk conditions
_CONDITION_EDUCATIONAL_DESCRIPTIONS: Dict[str, str] = {
    "diabetes": "statistical assessment based on glucose, insulin, body mass, and age indicators",
    "heart_disease": "statistical assessment based on cardiovascular markers, resting blood pressure, and cholesterol levels",
    "kidney_disease": "statistical assessment based on kidney filtration markers, electrolytes, and urinalysis indicators",
}

# Standard non-prescriptive guidance
_DEFAULT_FOLLOW_UP_GUIDANCE: List[str] = [
    "Review these verified laboratory results with your physician for clinical correlation.",
    "Bring this summary and your original laboratory report to your next medical appointment.",
    "Do not alter, stop, or start any medication or treatment regimen without professional medical advice.",
]

_DEFAULT_DOCTOR_QUESTIONS: List[str] = [
    "What do my specific test values indicate about my overall health status?",
    "Are there any recommended lifestyle, physical activity, or dietary modifications based on these results?",
    "When should I schedule repeat laboratory tests or follow-up health screenings?",
]

# Multilingual simulated summary templates
_SIMULATED_SUMMARIES: Dict[SupportedLanguage, str] = {
    SupportedLanguage.ENGLISH: (
        "This is a simulated educational explanation generated by the MedIntel mock GenAI provider. "
        "The report includes {n_analytes} verified laboratory finding(s) and {n_risks} statistical "
        "risk screening indicator(s). All test values and model scores reflect educational analysis only."
    ),
    SupportedLanguage.HINDI: (
        "यह मेडइंटेल मॉक जेनएआई प्रदाता द्वारा तैयार किया गया एक सिम्युलेटेड शैक्षणिक विवरण है। "
        "आपकी रिपोर्ट में {n_analytes} सत्यापित प्रयोगशाला परीक्षण और {n_risks} सांख्यिकीय जोखिम संकेतक "
        "शामिल हैं। यह केवल शैक्षणिक समझ के लिए है और कोई चिकित्सीय निदान नहीं है।"
    ),
    SupportedLanguage.MARATHI: (
        "हे मेडइंटेल मॉक जेनएआय प्रदात्याद्वारे तयार केलेले सिम्युलेटेड शैक्षणिक स्पष्टीकरण आहे. "
        "आपल्या अहवालात {n_analytes} पडताळणी केलेले प्रयोगशाळा निष्कर्ष आणि {n_risks} सांख्यिकीय जोखीम "
        "निर्देश समाविष्ट आहेत. हे केवळ शैक्षणिक मार्गदर्शनासाठी असून कोणतेही वैद्यकीय निदान नाही."
    ),
    SupportedLanguage.GUJARATI: (
        "આ મેડઇન્ટેલ મોક જેનએઆઈ પ્રદાતા દ્વારા તૈયાર કરાયેલ સિમ્યુલેટેડ શૈક્ષણિક ખુલાસો છે. "
        "તમારા અહેવાલમાં {n_analytes} ચકાસાયેલ પ્રયોગશાળા તારણો અને {n_risks} આંકડાકીય જોખમ સૂચકાંકો "
        "શામેલ છે. આ ફક્ત શૈક્ષણિક હેતુ માટે છે અને કોઈ તબીબી નિદાન નથી."
    ),
}


class MockGenAIProvider(BaseGenAIProvider):
    """Deterministic offline mock provider for testing and local development.

    Operates without network dependencies, API keys, or external resources.
    """

    @property
    def provider_name(self) -> str:
        return "mock"

    @property
    def model_name(self) -> str:
        return "mock-deterministic-v1"

    async def generate_explanation(
        self,
        request: GenAIExplainRequest,
    ) -> GenAIExplanationPayload:
        """Generate a deterministic, offline educational explanation.

        Args:
            request: Validated GenAIExplainRequest.

        Returns:
            GenAIExplanationPayload preserving all numbers, units, and categories.
        """
        n_analytes = len(request.analytes)
        n_risks = len(request.ml_risks)

        # 1. Build summary text
        summary = _SIMULATED_SUMMARIES[SupportedLanguage.ENGLISH].format(
            n_analytes=n_analytes,
            n_risks=n_risks,
        )

        if request.detail_level == DetailLevel.DETAILED:
            summary += (
                " Detailed review mode: Laboratory reference bounds are evaluated deterministically "
                "against clinical guidelines, and disease risk scores are estimated via classical "
                "supervised machine learning algorithms."
            )

        # 2. Build analyte findings
        findings: List[AnalyteExplanationItem] = []
        for analyte in request.analytes:
            # Format observed value with unit
            val_str = f"{analyte.value} {analyte.unit}".strip() if analyte.value is not None else "Not specified"
            classification_str = analyte.classification or "NOT_CLASSIFIED"

            # Lookup educational description
            key = (analyte.canonical_name or analyte.test_name).lower()
            desc = _ANALYTE_EDUCATIONAL_DESCRIPTIONS.get(
                key,
                f"{analyte.test_name} is a routine clinical laboratory analyte.",
            )

            explanation_text = (
                f"{desc} In this report, the observed measurement was {val_str}, "
                f"which Phase 6 evaluated as {classification_str}."
            )

            findings.append(
                AnalyteExplanationItem(
                    analyte_name=analyte.display_name or analyte.canonical_name or analyte.test_name,
                    observed_value=val_str,
                    classification=classification_str,
                    plain_language_meaning=explanation_text,
                )
            )

        # 3. Build risk explanations
        risk_explanations: List[RiskExplanationItem] = []
        for risk in request.ml_risks:
            cond_key = risk.condition.lower()
            cond_desc = _CONDITION_EDUCATIONAL_DESCRIPTIONS.get(
                cond_key,
                f"statistical screening evaluation for {risk.condition}",
            )

            prob_pct = f"{risk.risk_probability * 100:.1f}%"
            explanation_text = (
                f"The Phase 7 machine learning model ({risk.model_name or 'Classifier'}) "
                f"estimated a risk probability of {risk.risk_probability:.4f} ({prob_pct}) "
                f"for {risk.condition} based on {cond_desc}. This places the finding into the "
                f"{risk.risk_band} educational screening band. This probability is a statistical "
                "indicator and does NOT constitute a confirmed medical diagnosis."
            )

            risk_explanations.append(
                RiskExplanationItem(
                    condition=risk.condition,
                    model_probability=risk.risk_probability,
                    risk_band=risk.risk_band,
                    plain_language_explanation=explanation_text,
                )
            )

        # 4. Construct payload
        return GenAIExplanationPayload(
            summary=summary,
            findings=findings,
            risk_explanations=risk_explanations,
            follow_up_guidance=list(_DEFAULT_FOLLOW_UP_GUIDANCE),
            recommended_questions_for_doctor=list(_DEFAULT_DOCTOR_QUESTIONS),
        )

    async def translate_explanation(
        self,
        payload: GenAIExplanationPayload,
        target_language: SupportedLanguage,
    ) -> Tuple[GenAIExplanationPayload, Optional[str]]:
        """Perform mock translation while strictly preserving all clinical and numeric invariants.

        Args:
            payload: Source GenAIExplanationPayload.
            target_language: Target language.

        Returns:
            Tuple of (translated_payload, translated_summary_text).
        """
        if target_language == SupportedLanguage.ENGLISH:
            return payload, None

        n_analytes = len(payload.findings)
        n_risks = len(payload.risk_explanations)

        translated_summary = _SIMULATED_SUMMARIES.get(
            target_language,
            _SIMULATED_SUMMARIES[SupportedLanguage.ENGLISH],
        ).format(n_analytes=n_analytes, n_risks=n_risks)

        # Invariance preservation:
        # Create translated findings where observed_value and classification are identical
        translated_findings: List[AnalyteExplanationItem] = []
        for item in payload.findings:
            prefix = {
                SupportedLanguage.HINDI: "[हिंदी विवरण] ",
                SupportedLanguage.MARATHI: "[मराठी विवरण] ",
                SupportedLanguage.GUJARATI: "[ગુજરાતી વિગતો] ",
            }.get(target_language, "")

            translated_findings.append(
                AnalyteExplanationItem(
                    analyte_name=item.analyte_name,
                    observed_value=item.observed_value,      # INVARIANT: Exact number and unit
                    classification=item.classification,      # INVARIANT: Exact LOW/NORMAL/HIGH/CRITICAL
                    plain_language_meaning=f"{prefix}{item.plain_language_meaning}",
                )
            )

        # Create translated risk explanations where probability and band are identical
        translated_risks: List[RiskExplanationItem] = []
        for r in payload.risk_explanations:
            prefix = {
                SupportedLanguage.HINDI: "[हिंदी जोखिम] ",
                SupportedLanguage.MARATHI: "[मराठी जोखीम] ",
                SupportedLanguage.GUJARATI: "[ગુજરાતી જોખમ] ",
            }.get(target_language, "")

            translated_risks.append(
                RiskExplanationItem(
                    condition=r.condition,
                    model_probability=r.model_probability,    # INVARIANT: Exact float
                    risk_band=r.risk_band,                    # INVARIANT: Exact LOW/MODERATE/ELEVATED
                    plain_language_explanation=f"{prefix}{r.plain_language_explanation}",
                )
            )

        # Translated guidance
        guidance_prefix = {
            SupportedLanguage.HINDI: "[हिंदी मार्गदर्शन] ",
            SupportedLanguage.MARATHI: "[मराठी मार्गदर्शन] ",
            SupportedLanguage.GUJARATI: "[ગુજરાતી માર્ગદર્શન] ",
        }.get(target_language, "")

        translated_guidance = [f"{guidance_prefix}{g}" for g in payload.follow_up_guidance]
        translated_questions = [f"{guidance_prefix}{q}" for q in payload.recommended_questions_for_doctor]

        translated_payload = GenAIExplanationPayload(
            summary=translated_summary,
            findings=translated_findings,
            risk_explanations=translated_risks,
            follow_up_guidance=translated_guidance,
            recommended_questions_for_doctor=translated_questions,
        )

        return translated_payload, translated_summary

    async def check_health(self) -> Dict[str, Any]:
        """Verify mock provider availability."""
        return {
            "available": True,
            "provider": self.provider_name,
            "model": self.model_name,
            "mode": "offline_deterministic_mock",
            "network_required": False,
        }
